[16기 김병진] 배민문방구 Category/Item 페이지 데이터 매핑 완료
wecode-bootcamp-korea/baemin_store-frontend pull request #10
Opened 2021-01-18 05:28 UTC by rlaqudwls25

## 수정 사항 간략한 한줄 요약
- 백엔드 데이터와 서버  준비 되기전에 Mock data로 Category 페이지 와 item컴포넌트  배치 확인 후에 Category 리스트 페이지를  백엔드 데이터 가져와서 매핑 완료

		 
## 수정 사항들 자세한 내용
-  백엔드 데이터와 서버  준비 되기전에 Mock data로 Category 페이지 와 item컴포넌트  배치 확인 후에 Category 리스트 페이지를  백엔드 데이터 가져와서 매핑 완료

## 기타 질문 및 특이 사항
- 없습니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-19 02:55 UTC, Jun4928 requested changes
동료 개발자 입장에서 올려주신 코드를 봤다고 가정 해 보겠습니다.

컴포넌트의 이름과 그 안에서 사용되는 변수명들이 다음과 같습니다.
- Item 
- ItemList

이렇게 컴포넌트명과 변수명을 작성하시면 의미를 파악하기 어렵습니다.
개발자라면 누구나 데이터를 코드로 다룬다는 점을 알고 있습니다.
따라서, `data` `item` `info` 와 같이 의미를 전달 할 수 없는 변수명을 사용하지 않습니다. 

컴포넌트의 이름과 변수명만 보고도 **어떤 데이터**가 담겨있는지 의도를 드러내 주셔야 합니다. 

```js
// bad
export default class Item extends Component {
}

// good
export default class Product extends Component {
}
```
```js
// bad
this.state = {
  itemList: []
}

// good
this.state = {
  products: []
}
```

```js
// bad
itemList.map((item) => {
  return (
    <Item
      url = {item.url}
      sale = {item.sale}
      ...
    />
  )
})

// good
products.map((product) => {
  return (
    <Item
      url = {product.url}
      sale = {product.sale}
      ...
    />
  )
})
```

2021-01-19 02:59 UTC, Jun4928 commented on src/Pages/Category/Category.js
>                  />
map 으로 컴포넌트를 렌더링 할 때 **key props** 가 필수적으로 있어야 합니다. 
각각의 컴포넌트에 고유한 id 를 부여하고 호율적인 렌더링을 위해 존재합니다.
이 **key props** 가 없으면 개발자도구 콘솔창에도 빨간색으로 경고 메세지가 뜹니다.

앞으로 잊지 않고 꼭! 작성해주세요.

2021-01-19 04:32 UTC, rlaqudwls25 commented on src/Pages/Category/Category.js
>                  />
코드 수정해보겠습니다 !  감사합니다 !!

2021-01-20 02:31 UTC, Jun4928 requested changes

2021-01-20 02:31 UTC, Jun4928 commented on src/Pages/Category/Category.js
> +  }
1. **end, start** 의 변수명이 정확히 어떤 것을 의미하는지 명확하지 않습니다. 어떤 용도를 위해 선언 한 상태인가요?
2. 만약에 end 가 항상 start 에 특정한 수를 더한 값이라면 상태로 가지고 있을 필요가 없습니다. `start + 4` 이런 식으로 사용하면 되지 않을까요?
3. 두 함수를 하나의 함수로 리팩토링 할 수 있습니다. 다음 코드 스니펫을 참고 해 주세요.
<img width="1282" alt="Screen Shot 2021-01-20 at 11 28 39 AM" src="https://user-images.githubusercontent.com/63147802/105118932-ab839b80-5b12-11eb-93cc-2eab92be3cf4.png">

- 함수에 인자로 action type 을 받으면 증가시킬지 감소시킬지 결정 할 수 있습니다.
- 함수 안에 숫자나 문자열을 하드코딩 하는 습관을 고쳐야 합니다. 다른 사람이 하드코딩 된 숫자와 문자열의 의미를 알 수 없기 때문입니다.
- 우리는 함수, 더 나아가 앱, 그리고 소프트웨어를 설계 할 때 나 뿐만 아니라 다른 사람과 협업할 수 있는 코드를 구성해야 합니다.
- 의미의 부여는 **변수명** 과 **함수명** 부터 시작입니다.

2021-01-21 08:47 UTC, bonbon0202 reviewed
병진님!! 불필요한 주석 모두 삭제해주시고, 리뷰반영한 리팩토링 진행완료해주시면 좋겠습니다! :)

2021-01-21 08:47 UTC, bonbon0202 commented on src/Components/Item/Item.js
> +    //mock data
불필요한 주석 모두 삭제해주세요!!!

2021-01-21 08:47 UTC, bonbon0202 commented on src/Pages/Category/Category.js
> +  // }
삭제해주세요!!

2021-01-21 08:47 UTC, bonbon0202 commented on src/Pages/Category/Category.js
> +  }
페이지네이션 하실 예정이신가요?!

2021-01-21 08:47 UTC, bonbon0202 commented on src/Pages/Category/Category.js
> +    })
리뷰 반영 된건가요?! 하나의 함수로 합칠 수 있겠습니다.

2021-01-21 08:56 UTC, rlaqudwls25 commented on src/Pages/Category/Category.js
> +  }
페이지네이션 구현 못할거같습니다 ㅜ

2021-01-21 08:56 UTC, rlaqudwls25 commented on src/Pages/Category/Category.js
> +    })
이것도 페이지네이션 구현 할려고 쓴 코드인데 못할거같아서 삭제하겠습니다 !

2021-01-21 08:59 UTC, rlaqudwls25 commented on src/Pages/Category/Category.js
> +  // }
일단 mockdata로 화면에 데이터를 뿌려주고 있긴한데  위에 코드는 백분들과 mapping해서 성공한 코드라서 지울 수가 없습니다!

2021-01-21 09:00 UTC, rlaqudwls25 commented on src/Components/Item/Item.js
> +    //mock data
이것도 mapping 할때 쓰는 props들이라 못지웁니다 ㅜ

2021-01-22 04:51 UTC, merged